<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My PHP Website</title>
    <style>
        body {
            font-family: sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background: #e8eaf6;
            margin: 0;
        }

        .card {
            background: white;
            padding: 2rem;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        .php-info {
            color: #5c6bc0;
            font-weight: bold;
        }
    </style>
</head>

<body>
    <div class="card">
        <h1>Welcome to PHP!</h1>
        <p>This page is generated by PHP.</p>
        <p class="php-info">PHP Version: <?php echo phpversion(); ?></p>
        <p>Server Time: <?php echo date('Y-m-d H:i:s'); ?></p>
    </div>
</body>

</html>